import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google';
import './globals.css';

// Configure Inter
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

// Configure Poppins
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Add the weights you actually need
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
